[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.composer",
    "php82Extensions.mysql",
    "php82Extensions.pdo_mysql",
    "php82Extensions.zip",
    "php82Extensions.gd",
    "php82Extensions.bcmath",
    "php82Extensions.intl",
    "php82Extensions.fileinfo",
    "php82Extensions.xml",
    "nodejs_20"
]

[phases.build]
cmds = [
    "npm install && npm run build",
    "composer install --optimize-autoloader --no-dev --ignore-platform-reqs"
]

[start]
cmd = "php artisan migrate --force && php artisan serve --host 0.0.0.0 --port $PORT"
